### post blog 1
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Test Blog2",
  "author": "Author Name",
  "url": "http://example2.com",
  "likes": 5,
  "username": "testuser"
}