### post blog 1
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Introduction to Fullstack Development",
  "author": "John Doe",
  "url": "https://fullstack.example.com",
  "likes": 10
}